// cards
const CREATE_AND_ADD_CARD_TO_DECK = 'CREATE_AND_ADD_CARD_TO_DECK'
const GET_CARD_BY_ID = 'GET_CARD_BY_ID'

// decks
const CREATE_DECK = 'CREATE_DECK'
const RECEIVE_DECKS = 'RECEIVE_DECKS'

// quiz
const START_QUIZ = 'START_QUIZ'

export {
    CREATE_AND_ADD_CARD_TO_DECK,
    GET_CARD_BY_ID,
    CREATE_DECK,
    RECEIVE_DECKS,
    START_QUIZ,
}